//! Bridge between the Flutter app and `bandall-authenticator-core`.
//!
//! Deliberately thin: it exposes the pure logic as plain data and keeps no
//! state. Everything that has to survive a restart — the accounts — is stored
//! by the Dart side in platform secure storage (Keystore/Keychain), so the
//! secret never lives in a Rust global, in a file the app owns, or in a
//! `SharedPreferences` blob.
//!
//! That split is also what makes the app work in airplane mode: nothing here
//! opens a socket, and there is no network code to accidentally call.
//!
//! # `unsafe` policy
//!
//! `AGENTS.md` forbids `unsafe_code` in every crate. This crate cannot satisfy
//! that literally: crossing into Dart requires an FFI boundary, and
//! `flutter_rust_bridge`'s generated glue is where it lives. The rule is
//! therefore enforced as tightly as the tooling allows:
//!
//! - `api.rs` (hand-written) carries `#![forbid(unsafe_code)]`.
//! - The crate root `deny`s `unsafe_code`.
//! - `frb_generated` is the **single** module that lifts it, by name and with
//!   this justification. It is machine-written, committed as generated, and
//!   reviewed like any other diff.
//!
//! Writing the boundary by hand would mean *more* `unsafe`, not less, which is
//! the opposite of what the rule is for.
#![deny(unsafe_code)]

mod api;

pub use api::*;

#[cfg(test)]
mod tests;

/// Generated by flutter_rust_bridge. Committed to the repository so a fresh
/// checkout can build without running codegen first; `just mobile-generate`
/// rewrites it when the API changes.
///
/// The `allow` here is the only one in the crate; see the module docs above.
#[allow(unsafe_code)]
#[rustfmt::skip]
mod frb_generated;
