// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_snapshot`, `to_snapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Parses an `otpauth://` URI, which is what a QR scan produces.
///
/// Errors are deliberately opaque: a malformed QR must not tell the user (or a
/// malicious QR) which part parsed and which did not.
///
/// Synchronous: parsing is string work with no I/O, and making the UI await a
/// future for it would only add a frame of flicker.
AccountView parseOtpauth({required String uri}) =>
    RustLib.instance.api.crateApiParseOtpauth(uri: uri);

/// Builds an account from manual entry (no QR available).
///
/// Synchronous for the same reason as `parse_otpauth`: it validates strings and
/// a Base32 secret, nothing more.
AccountView manualAccount({
  required String issuer,
  required String name,
  required String algorithm,
  required int digits,
  required BigInt periodSecs,
  required String secretBase32,
}) => RustLib.instance.api.crateApiManualAccount(
  issuer: issuer,
  name: name,
  algorithm: algorithm,
  digits: digits,
  periodSecs: periodSecs,
  secretBase32: secretBase32,
);

/// Generates the code for `unix_secs`.
///
/// The time is a parameter, never `SystemTime::now()`: it is what makes the
/// whole path testable, and what lets the app show a code for a chosen instant
/// when the user is checking a clock problem.
///
/// Synchronous: it is one HMAC, and the UI redraws it every second.
CodeView codeAt({required AccountView view, required BigInt unixSecs}) =>
    RustLib.instance.api.crateApiCodeAt(view: view, unixSecs: unixSecs);

/// Compares the device clock against a reference (the server's time from the
/// last successful verification).
SkewView skew({required BigInt deviceSecs, required BigInt referenceSecs}) =>
    RustLib.instance.api.crateApiSkew(
      deviceSecs: deviceSecs,
      referenceSecs: referenceSecs,
    );

/// Encrypts the accounts under `passphrase` (Argon2id + XChaCha20-Poly1305).
///
/// This is the *optional* backup: the app does not upload anything anywhere on
/// its own, and the string this returns is the user's to keep.
///
/// **Asynchronous on purpose.** Argon2id is tuned to be slow (19 MiB, two
/// passes): running it synchronously would freeze the UI for a noticeable
/// moment. It stays on the async runtime so the spinner actually spins.
Future<String> exportBackup({
  required List<AccountView> accounts,
  required String passphrase,
}) => RustLib.instance.api.crateApiExportBackup(
  accounts: accounts,
  passphrase: passphrase,
);

/// Restores accounts from an encrypted backup.
///
/// A wrong passphrase and a tampered file are the same error on purpose: the
/// envelope is authenticated, so there is nothing useful to tell apart.
///
/// Asynchronous for the same reason as `export_backup`: it derives a key with
/// Argon2id before it can say "no".
Future<List<AccountView>> importBackup({
  required String payload,
  required String passphrase,
}) => RustLib.instance.api.crateApiImportBackup(
  payload: payload,
  passphrase: passphrase,
);

/// Whether a Base32 secret and its parameters are usable, for manual entry as
/// the user types.
///
/// Goes through the same constructor the account will use, so "valid here"
/// means "will work", not "looks like Base32".
///
/// Synchronous: it runs on every keystroke of the manual-entry field.
bool isValidSecret({
  required String secretBase32,
  required String algorithm,
  required int digits,
  required BigInt periodSecs,
}) => RustLib.instance.api.crateApiIsValidSecret(
  secretBase32: secretBase32,
  algorithm: algorithm,
  digits: digits,
  periodSecs: periodSecs,
);

/// One account as the UI sees it: everything needed to draw a row and generate
/// the current code, and nothing that requires holding Rust state.
///
/// `secret_base32` is here because the app has to persist it: the Dart side
/// hands this struct to platform secure storage (Keystore/Keychain) and reads
/// it back on launch. It must never be written to an unencrypted store, logged,
/// or put in a widget's state.
class AccountView {
  /// Issuer label, e.g. `BandAll`.
  final String issuer;

  /// Account label, e.g. `alice@example.com`.
  final String name;

  /// Secret as strict Base32 (persisted by the app, never logged).
  final String secretBase32;

  /// `SHA1`, `SHA256` or `SHA512`.
  final String algorithm;

  /// Digit count (6-8).
  final int digits;

  /// Period in seconds.
  final BigInt periodSecs;

  const AccountView({
    required this.issuer,
    required this.name,
    required this.secretBase32,
    required this.algorithm,
    required this.digits,
    required this.periodSecs,
  });

  @override
  int get hashCode =>
      issuer.hashCode ^
      name.hashCode ^
      secretBase32.hashCode ^
      algorithm.hashCode ^
      digits.hashCode ^
      periodSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          issuer == other.issuer &&
          name == other.name &&
          secretBase32 == other.secretBase32 &&
          algorithm == other.algorithm &&
          digits == other.digits &&
          periodSecs == other.periodSecs;
}

/// A code and how long it lasts.
class CodeView {
  /// The current code, zero padded to `digits`.
  final String code;

  /// Seconds until it rotates (1..=period).
  final BigInt secondsRemaining;

  const CodeView({required this.code, required this.secondsRemaining});

  @override
  int get hashCode => code.hashCode ^ secondsRemaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodeView &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          secondsRemaining == other.secondsRemaining;
}

/// Clock drift verdict, for the "your phone's clock looks off" banner.
class SkewView {
  /// Absolute difference in seconds.
  final BigInt seconds;

  /// Whether it exceeds the warning threshold (three steps).
  final bool warns;

  const SkewView({required this.seconds, required this.warns});

  @override
  int get hashCode => seconds.hashCode ^ warns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkewView &&
          runtimeType == other.runtimeType &&
          seconds == other.seconds &&
          warns == other.warns;
}
