// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1899506582;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'bandall_authenticator_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  CodeView crateApiCodeAt({
    required AccountView view,
    required BigInt unixSecs,
  });

  Future<String> crateApiExportBackup({
    required List<AccountView> accounts,
    required String passphrase,
  });

  Future<List<AccountView>> crateApiImportBackup({
    required String payload,
    required String passphrase,
  });

  bool crateApiIsValidSecret({
    required String secretBase32,
    required String algorithm,
    required int digits,
    required BigInt periodSecs,
  });

  AccountView crateApiManualAccount({
    required String issuer,
    required String name,
    required String algorithm,
    required int digits,
    required BigInt periodSecs,
    required String secretBase32,
  });

  AccountView crateApiParseOtpauth({required String uri});

  SkewView crateApiSkew({
    required BigInt deviceSecs,
    required BigInt referenceSecs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  CodeView crateApiCodeAt({
    required AccountView view,
    required BigInt unixSecs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_account_view(view, serializer);
          sse_encode_u_64(unixSecs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_code_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCodeAtConstMeta,
        argValues: [view, unixSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCodeAtConstMeta =>
      const TaskConstMeta(debugName: "code_at", argNames: ["view", "unixSecs"]);

  @override
  Future<String> crateApiExportBackup({
    required List<AccountView> accounts,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_account_view(accounts, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportBackupConstMeta,
        argValues: [accounts, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportBackupConstMeta => const TaskConstMeta(
    debugName: "export_backup",
    argNames: ["accounts", "passphrase"],
  );

  @override
  Future<List<AccountView>> crateApiImportBackup({
    required String payload,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(payload, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_account_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportBackupConstMeta,
        argValues: [payload, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportBackupConstMeta => const TaskConstMeta(
    debugName: "import_backup",
    argNames: ["payload", "passphrase"],
  );

  @override
  bool crateApiIsValidSecret({
    required String secretBase32,
    required String algorithm,
    required int digits,
    required BigInt periodSecs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secretBase32, serializer);
          sse_encode_String(algorithm, serializer);
          sse_encode_u_8(digits, serializer);
          sse_encode_u_64(periodSecs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsValidSecretConstMeta,
        argValues: [secretBase32, algorithm, digits, periodSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsValidSecretConstMeta => const TaskConstMeta(
    debugName: "is_valid_secret",
    argNames: ["secretBase32", "algorithm", "digits", "periodSecs"],
  );

  @override
  AccountView crateApiManualAccount({
    required String issuer,
    required String name,
    required String algorithm,
    required int digits,
    required BigInt periodSecs,
    required String secretBase32,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(issuer, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(algorithm, serializer);
          sse_encode_u_8(digits, serializer);
          sse_encode_u_64(periodSecs, serializer);
          sse_encode_String(secretBase32, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiManualAccountConstMeta,
        argValues: [issuer, name, algorithm, digits, periodSecs, secretBase32],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiManualAccountConstMeta => const TaskConstMeta(
    debugName: "manual_account",
    argNames: [
      "issuer",
      "name",
      "algorithm",
      "digits",
      "periodSecs",
      "secretBase32",
    ],
  );

  @override
  AccountView crateApiParseOtpauth({required String uri}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiParseOtpauthConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseOtpauthConstMeta =>
      const TaskConstMeta(debugName: "parse_otpauth", argNames: ["uri"]);

  @override
  SkewView crateApiSkew({
    required BigInt deviceSecs,
    required BigInt referenceSecs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(deviceSecs, serializer);
          sse_encode_u_64(referenceSecs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_skew_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSkewConstMeta,
        argValues: [deviceSecs, referenceSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSkewConstMeta => const TaskConstMeta(
    debugName: "skew",
    argNames: ["deviceSecs", "referenceSecs"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountView dco_decode_account_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AccountView(
      issuer: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      secretBase32: dco_decode_String(arr[2]),
      algorithm: dco_decode_String(arr[3]),
      digits: dco_decode_u_8(arr[4]),
      periodSecs: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountView dco_decode_box_autoadd_account_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_view(raw);
  }

  @protected
  CodeView dco_decode_code_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CodeView(
      code: dco_decode_String(arr[0]),
      secondsRemaining: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  List<AccountView> dco_decode_list_account_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_account_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SkewView dco_decode_skew_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SkewView(
      seconds: dco_decode_u_64(arr[0]),
      warns: dco_decode_bool(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountView sse_decode_account_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_issuer = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_secretBase32 = sse_decode_String(deserializer);
    var var_algorithm = sse_decode_String(deserializer);
    var var_digits = sse_decode_u_8(deserializer);
    var var_periodSecs = sse_decode_u_64(deserializer);
    return AccountView(
      issuer: var_issuer,
      name: var_name,
      secretBase32: var_secretBase32,
      algorithm: var_algorithm,
      digits: var_digits,
      periodSecs: var_periodSecs,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountView sse_decode_box_autoadd_account_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_view(deserializer));
  }

  @protected
  CodeView sse_decode_code_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_secondsRemaining = sse_decode_u_64(deserializer);
    return CodeView(code: var_code, secondsRemaining: var_secondsRemaining);
  }

  @protected
  List<AccountView> sse_decode_list_account_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AccountView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_account_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SkewView sse_decode_skew_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seconds = sse_decode_u_64(deserializer);
    var var_warns = sse_decode_bool(deserializer);
    return SkewView(seconds: var_seconds, warns: var_warns);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_view(AccountView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.issuer, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.secretBase32, serializer);
    sse_encode_String(self.algorithm, serializer);
    sse_encode_u_8(self.digits, serializer);
    sse_encode_u_64(self.periodSecs, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account_view(
    AccountView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_view(self, serializer);
  }

  @protected
  void sse_encode_code_view(CodeView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_u_64(self.secondsRemaining, serializer);
  }

  @protected
  void sse_encode_list_account_view(
    List<AccountView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_account_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_skew_view(SkewView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.seconds, serializer);
    sse_encode_bool(self.warns, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
