//! Stored rows. Times are Unix seconds (`i64`); steps map to `u64` with a
//! corruption check, so a tampered `last_step` fails closed instead of
//! wrapping.

use sqlx::FromRow;

use crate::error::Error;

/// Tenant row.
#[derive(Debug, Clone, FromRow)]
pub struct Tenant {
    /// Tenant id.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
}

/// Subject (user/device) row.
#[derive(Debug, Clone, FromRow)]
pub struct Subject {
    /// Subject id.
    pub id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Caller-provided stable identifier (unique per tenant).
    pub external_id: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
}

/// TOTP factor row, mirroring the sealed secret plus policy state.
#[derive(Debug, Clone, FromRow)]
pub struct Factor {
    /// Factor id.
    pub id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Owning subject.
    pub subject_id: String,
    /// `pending` or `active`.
    pub status: String,
    /// Seal format version.
    pub secret_version: i16,
    /// KEK id that wrapped the DEK.
    pub kek_id: String,
    /// Wrapped DEK bytes.
    pub wrapped_dek: Vec<u8>,
    /// DEK-wrapping nonce.
    pub wrapped_nonce: Vec<u8>,
    /// Data nonce.
    pub nonce: Vec<u8>,
    /// Encrypted secret bytes.
    pub ciphertext: Vec<u8>,
    /// Algorithm name (`SHA1`/`SHA256`/`SHA512`).
    pub algorithm: String,
    /// Digit count.
    pub digits: i16,
    /// Period in seconds.
    pub period: i64,
    /// Last accepted TOTP step (`None` = never verified).
    pub last_step: Option<i64>,
    /// Learned clock drift in steps (bounded to ±5).
    pub drift_steps: i64,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Confirmation time (Unix seconds, `None` while pending).
    pub confirmed_at: Option<i64>,
}

impl Factor {
    /// `last_step` as a step counter, rejecting tampered negatives.
    pub fn last_step_u64(&self) -> Result<Option<u64>, Error> {
        self.last_step
            .map(|s| u64::try_from(s).map_err(|_| Error::CorruptRow))
            .transpose()
    }

    /// Learned clock drift in steps (bounded, see verification).
    pub fn drift(&self) -> i64 {
        self.drift_steps
    }
}

/// Stored recovery-code hash with its consumption time.
#[derive(Debug, Clone, FromRow)]
pub struct RecoveryHash {
    /// PHC hash string.
    pub code_hash: String,
    /// Consumption time (Unix seconds, `None` = unused).
    pub used_at: Option<i64>,
}

/// Fresh random factor id. Generated by the caller so the same value seals
/// the secret (row-identity AAD) before insertion.
#[must_use]
pub fn new_factor_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Fresh random session or family id.
#[must_use]
pub fn new_session_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Session row: local login session, revocable by id.
#[derive(Debug, Clone, FromRow)]
pub struct Session {
    /// Session id (`sid` claim, revocation handle).
    pub id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Owning subject.
    pub subject_id: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Revocation time (`None` = live).
    pub revoked_at: Option<i64>,
}

/// Refresh-token row: hash only, single-use with family revocation.
#[derive(Debug, Clone, FromRow)]
pub struct RefreshEntry {
    /// SHA-256 hash of the opaque token (hex).
    pub code_hash: String,
    /// Rotation family (reuse revokes the whole family).
    pub family_id: String,
    /// Owning session.
    pub session_id: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Expiry time (Unix seconds).
    pub expires_at: i64,
    /// Consumption time (`None` = live).
    pub used_at: Option<i64>,
    /// Family-revocation time (`None` = live).
    pub revoked_at: Option<i64>,
}

/// New refresh token to persist.
#[derive(Debug, Clone)]
pub struct NewRefresh {
    /// SHA-256 hash of the opaque token (hex).
    pub code_hash: String,
    /// Rotation family.
    pub family_id: String,
    /// Owning session.
    pub session_id: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Expiry time (Unix seconds).
    pub expires_at: i64,
}

/// API client row: sealed HMAC key plus scopes.
#[derive(Debug, Clone, FromRow)]
pub struct ApiClient {
    /// Public key identifier (`X-Key-Id`).
    pub key_id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Seal format version.
    pub sealed_version: i16,
    /// KEK id that wrapped the DEK.
    pub kek_id: String,
    /// Wrapped DEK bytes.
    pub wrapped_dek: Vec<u8>,
    /// DEK-wrapping nonce.
    pub wrapped_nonce: Vec<u8>,
    /// Data nonce.
    pub nonce: Vec<u8>,
    /// Encrypted key bytes.
    pub ciphertext: Vec<u8>,
    /// Space-separated scopes.
    pub scopes: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Revocation time (`None` = live).
    pub revoked_at: Option<i64>,
}

/// New API client to insert.
#[derive(Debug, Clone)]
pub struct NewApiClient {
    /// Public key identifier.
    pub key_id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Seal format version.
    pub sealed_version: i16,
    /// KEK id that wrapped the DEK.
    pub kek_id: String,
    /// Wrapped DEK bytes.
    pub wrapped_dek: Vec<u8>,
    /// DEK-wrapping nonce.
    pub wrapped_nonce: Vec<u8>,
    /// Data nonce.
    pub nonce: Vec<u8>,
    /// Encrypted key bytes.
    pub ciphertext: Vec<u8>,
    /// Space-separated scopes.
    pub scopes: String,
    /// Creation time (Unix seconds).
    pub created_at: i64,
}

/// WebSocket connection-ticket row (ADR-0017): the hash only, with a hard
/// lifetime and an atomic claim.
#[derive(Debug, Clone, FromRow)]
pub struct WsTicketEntry {
    /// SHA-256 hash of the opaque ticket (hex). Primary key.
    pub code_hash: String,
    /// Owning session (`sid` the connection re-validates against).
    pub session_id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Owning subject.
    pub subject_id: String,
    /// Expiry of the access token that obtained the ticket: the hard ceiling
    /// for the connection's life.
    pub access_expires_at: i64,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Ticket expiry (Unix seconds): `created_at + WS_TICKET_TTL_SECS`.
    pub expires_at: i64,
    /// Consumption time (`None` = unused); claiming is atomic.
    pub used_at: Option<i64>,
}

/// A ticket to persist.
#[derive(Debug, Clone)]
pub struct NewWsTicket {
    /// SHA-256 hash of the opaque ticket (hex).
    pub code_hash: String,
    /// Owning session.
    pub session_id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Owning subject.
    pub subject_id: String,
    /// Expiry of the access token that obtained the ticket.
    pub access_expires_at: i64,
    /// Creation time (Unix seconds).
    pub created_at: i64,
    /// Ticket expiry (Unix seconds).
    pub expires_at: i64,
}

/// Audit log entry: hash-chained for tamper evidence.
#[derive(Debug, Clone, FromRow)]
pub struct AuditEntry {
    /// Sequence number.
    pub seq: i64,
    /// Event time (Unix seconds).
    pub ts: i64,
    /// Acting tenant.
    pub tenant_id: String,
    /// Acting subject.
    pub subject_id: String,
    /// Event name (`mfa.verified`, ...).
    pub event: String,
    /// Previous entry hash (32 zero bytes at genesis).
    pub prev_hash: Vec<u8>,
    /// Entry hash.
    pub hash: Vec<u8>,
    /// Chain format that produced `hash`: `1` = legacy unkeyed SHA-256,
    /// `2` = keyed HMAC-SHA-256 (see `NewAudit::CHAIN_V2`).
    pub chain_version: i16,
}

/// An audit entry to append. The hash and `prev_hash` are **not** supplied by
/// the caller: the store computes them inside the append transaction, so the
/// chain cannot fork under concurrency.
#[derive(Debug, Clone)]
pub struct NewAudit {
    /// Event time (Unix seconds).
    pub ts: i64,
    /// Acting tenant.
    pub tenant_id: String,
    /// Acting subject.
    pub subject_id: String,
    /// Event name (`mfa.verified`, ...).
    pub event: String,
    /// Chain format to write.
    pub chain_version: i16,
}

impl NewAudit {
    /// Keyed HMAC-SHA-256 chain (current format).
    pub const CHAIN_V2: i16 = 2;
    /// Legacy unkeyed SHA-256 chain, accepted for verification only.
    pub const CHAIN_V1: i16 = 1;
}

/// Computes the chain link hash for one entry given the previous link.
///
/// Implemented by the caller (`bandall-api::audit::AuditChain`) so this crate
/// stays free of key material and of crypto policy: the store only guarantees
/// that the hash is derived from the real predecessor inside the transaction.
pub trait AuditHasher: Send + Sync {
    /// Returns the hash linking `prev_hash` to `entry`.
    ///
    /// Returning `Err` aborts the append: the transaction rolls back rather
    /// than storing a row whose chain link cannot be verified.
    fn link(&self, entry: &NewAudit, prev_hash: &[u8]) -> Result<Vec<u8>, Error>;
}

impl<T: AuditHasher + ?Sized> AuditHasher for std::sync::Arc<T> {
    fn link(&self, entry: &NewAudit, prev_hash: &[u8]) -> Result<Vec<u8>, Error> {
        (**self).link(entry, prev_hash)
    }
}
/// New factor to insert.
#[derive(Debug, Clone)]
pub struct NewFactor {
    /// Factor id (fresh UUID from `new_factor_id`).
    pub id: String,
    /// Owning tenant.
    pub tenant_id: String,
    /// Owning subject.
    pub subject_id: String,
    /// Initial status (`pending` for enrolment).
    pub status: String,
    /// Seal format version.
    pub secret_version: i16,
    /// KEK id that wrapped the DEK.
    pub kek_id: String,
    /// Wrapped DEK bytes.
    pub wrapped_dek: Vec<u8>,
    /// DEK-wrapping nonce.
    pub wrapped_nonce: Vec<u8>,
    /// Data nonce.
    pub nonce: Vec<u8>,
    /// Encrypted secret bytes.
    pub ciphertext: Vec<u8>,
    /// Algorithm name.
    pub algorithm: String,
    /// Digit count.
    pub digits: i16,
    /// Period in seconds.
    pub period: i64,
    /// Creation time (Unix seconds).
    pub created_at: i64,
}
