global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: bandall
    metrics_path: /metrics
    static_configs:
      - targets: ["bandall:8080"]

alerting:
  alertmanagers: []
