#!/usr/bin/env bash
# Flutter + Android toolchain, user-space.
#
# No `sudo` on this machine (it asks for a password), so nothing is installed
# system-wide: the JDK, the Android SDK and Flutter all land under `$HOME/opt`
# and are reached through the environment this script exports. That is enough to
# develop the app, run the test suite and build a release APK.
#
# iOS is not and cannot be covered here: it needs macOS and Xcode.
set -euo pipefail

OPT="$HOME/opt"
mkdir -p "$OPT"

log() { printf '\n== %s\n' "$1"; }

# --------------------------------------------------------------------------
# 1. JDK 17 (Temurin). Android Gradle Plugin needs 17+; Flutter's Android
#    toolchain is validated against it.
# --------------------------------------------------------------------------
if [ ! -x "$OPT/jdk/bin/java" ]; then
    log "JDK 17 (Temurin)"
    JDK_URL="https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse"
    curl -fsSL "$JDK_URL" -o "$OPT/jdk.tar.gz"
    mkdir -p "$OPT/jdk-extract"
    tar -xzf "$OPT/jdk.tar.gz" -C "$OPT/jdk-extract"
    rm -f "$OPT/jdk.tar.gz"
    mv "$OPT/jdk-extract"/*/ "$OPT/jdk"
    rm -rf "$OPT/jdk-extract"
fi
export JAVA_HOME="$OPT/jdk"
export PATH="$JAVA_HOME/bin:$PATH"
java -version

# --------------------------------------------------------------------------
# 2. Android SDK command-line tools, then the platforms and build-tools the
#    project pins. Installed with `sdkmanager --licenses` accepted up front so
#    no step stops waiting for a y/n prompt.
# --------------------------------------------------------------------------
ANDROID_HOME="$HOME/Android/Sdk"
if [ ! -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
    log "Android SDK command-line tools"
    mkdir -p "$ANDROID_HOME/cmdline-tools"
    CMDLINE_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    curl -fsSL "$CMDLINE_URL" -o "$OPT/cmdline-tools.zip"
    unzip -q -o "$OPT/cmdline-tools.zip" -d "$ANDROID_HOME/cmdline-tools"
    rm -f "$OPT/cmdline-tools.zip"
    # The zip unpacks into `cmdline-tools/`; sdkmanager requires the
    # `cmdline-tools/latest/` layout or it ignores itself.
    mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
fi
export ANDROID_HOME
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

log "Android platform, build-tools, NDK and platform-tools"
# NDK: needed because the authenticator core is Rust and has to be cross
# compiled for the four Android ABIs.
yes 2>/dev/null | sdkmanager --licenses >/dev/null 2>&1 || true
sdkmanager --install \
    "platform-tools" \
    "platforms;android-35" \
    "build-tools;35.0.0" \
    "ndk;27.2.12479018" \
    "cmake;3.22.1" >/dev/null

# --------------------------------------------------------------------------
# 3. Flutter.
# --------------------------------------------------------------------------
if [ ! -x "$OPT/flutter/bin/flutter" ]; then
    log "Flutter SDK"
    git clone --depth 1 -b stable https://github.com/flutter/flutter.git "$OPT/flutter"
fi
export PATH="$OPT/flutter/bin:$PATH"
# Git is a hard requirement for the Flutter tool, and this clone is shallow.
git config --global --add safe.directory "$OPT/flutter"

log "Flutter and Dart versions"
flutter --version
dart --version

# --------------------------------------------------------------------------
# 4. A shell snippet that re-exports the environment, so a new terminal (or an
#    IDE) can pick the toolchain up without re-running this script.
# --------------------------------------------------------------------------
ENV_FILE="$HOME/.config/bandall-flutter-env.sh"
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by tests/mobile/install_toolchain.sh. Source it to get Flutter,
# the JDK and the Android SDK on PATH.
export JAVA_HOME="$OPT/jdk"
export ANDROID_HOME="$ANDROID_HOME"
export PATH="\$JAVA_HOME/bin:\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:$OPT/flutter/bin:\$PATH"
export PUB_CACHE="$HOME/.pub-cache"
EOF

log "done"
cat <<EOF

Toolchain installed under \$HOME (no system packages touched):
  JDK17        $OPT/jdk
  Android SDK  $ANDROID_HOME
  Flutter      $OPT/flutter

To use it in a new shell:
  source $ENV_FILE

iOS builds are out of reach here: they need macOS and Xcode.
EOF